version: "3.7"
services:
  web-server:
    build:
      dockerfile: php/Dockerfile
      context: .
    restart: unless-stopped
    volumes:
      - "./html/:/var/www/html/"
    ports:
      - "8000:80"

  ftp:
    build:
      dockerfile: Dockerfile
      context: ftp/
    volumes:
      - "./html/users/:/ftp/"
    restart: unless-stopped
    ports:
      - "2121:21"

  mariadb:
    image: tobi312/rpi-mariadb:latest
    restart: unless-stopped
    env_file:
      - environment.yml
    volumes:
      - mysql-data:/var/lib/mysql
volumes:
  mysql-data:
