version: "3.7"
services:
  web-server:
    build:
      dockerfile: Dockerfile
      context: php/
    restart: unless-stopped
    volumes:
      - "./html/:/var/www/html/"
    ports:
      - 80:80

  ftp:
    build:
      dockerfile: Dockerfile
      context: ftp/
    volumes:
      - "./html/users/:/ftp/"
      - "./ftp/users.json:/ftp/users.json"
    restart: unless-stopped
    network_mode: "host"
    env_file:
      - environment.yml

  mariadb:
    image: tobi312/rpi-mariadb:latest
    restart: unless-stopped
    env_file:
      - environment.yml
    ports:
      - 3306:3306
    volumes:
      - mysql-data:/var/lib/mysql
volumes:
  mysql-data:
