# SQL
MYSQL_ROOT_PASSWORD="MARIADB|secret"
PUID=1000
PGID=1000
TZ=Europe/Paris

# FTP
BANNER="Basic FTP − NOT FOR PRODUCTION"
MAX_CONNS=100
MAX_CONNS_PER_IP=5
PASSWORD_PREFIX=RPI|
PASSWORD_SUFFIX=|LAMP
